Update the plugin workflow templates
Sarrus1/sourcepawn-vscode pull request #282
Opened 2023-02-18 21:57 UTC by Zabaniya001

The extension's workflow templates are a great way to quickly have a proper way to build and release plugins on github.
However, they're out-of-date ( they can't create releases anymore ) and lack some nice-to-have functionalities.

2023-02-18 21:58 UTC, Zabaniya001 commented on templates/main_template.yml
> +          version: "1.11.x"
The stable version is now 1.11, not 1.10 anymore.

2023-02-18 22:00 UTC, Zabaniya001 commented on templates/main_template.yml
> +          spcomp -w234 -O2 -v2 -i"include" -o"../plugins/${plugin_name}.smx" ${plugin_name}.sp
Whilst it'd be good practice to not have any warnings in your plugin especially when you're releasing them, it's not enforced by default ( neither by SPComp nor by the extension itself ).

2023-02-18 22:02 UTC, Zabaniya001 commented on templates/main_template.yml
> +          zip -qq -y -r ${{ github.event.repository.name }}-${{ steps.setup_sp.outputs.plugin-version }}.zip configs plugins scripting extensions gamedata translations data
Plugins generally require or have multiple files, for example a gamedata file or some translation files. There is no reason to zip only the plugin file. This zips everything even if certain folders don't exist.

2023-02-18 22:03 UTC, Zabaniya001 commented on templates/main_template.yml
> +      contents: write
It is now required by Github Actions to have this permission to make releases. If the action doesn't have it, the last step will fail.

2023-02-18 22:04 UTC, Zabaniya001 commented on templates/main_template.yml
> +    if: "!contains(github.event.head_commit.message, '[ci]')"
Nice to have. Sometimes you'll be changing things that have nothing to do with the plugin itself ( e.g. readme file ). No reason to run the workflow in those cases, so we can do it by adding [ci] inside the commit name.

2023-02-18 22:14 UTC, Zabaniya001 commented
I've tested these changed on a private repository and also generating them by swapping the original files in the extension's vscode folder.

2023-03-22 22:47 UTC, Sarrus1 requested changes
Instead of having a "skip ci" commit, I think it makes more sense to only trigger the build when a new release is created via the Github UI. This allows several things:
- Only create a release when the user wants it.
- Avoid having "empty commits" with just "[ci]" in them.
- Encourage plugin versionning.

Can you please use [this workflow as a template](https://github.com/surftimer/SurfTimer-discord/blob/ebfafd4306539cf3c36e86b5c285b536f770457c/.github/workflows/master.yml#LL3-L5C21) for using this method?

2023-03-22 22:47 UTC, Sarrus1 commented
Hi @Zabaniya001 thanks a lot for the PR, I'm finally going to merge it, after you make the requested changes.
Again, sorry for the delay, was busy porting to the new LSP :)

2023-03-23 00:25 UTC, Zabaniya001 commented
Alright, I've made the requested change.
Personally, I'm leaning more towards the older approach ( build on commit ) since most people would rather have a "drop and forget" method to compile their repositories ( including me ) and they'll most likely forget to make a new tag in the first place.

If you don't want to compile it, just put in the commit name the `[ci]` tag and you're set. Otherwise, it'll compile and just replace the artifacts, which is not a big deal. 

I don't think this will make people version their plugins better and it'll end up just being a hassle.

Though, ultimately I don't mind the change.

2023-03-23 00:27 UTC, Zabaniya001 commented on templates/main_template.yml
> +          tag: ${{ github.ref_name }}
If the release tag doesn't match the version present in the .sp, it'll just be an empty release.

2023-03-23 22:35 UTC, merged

2023-03-23 22:35 UTC, Sarrus1 commented
Merged, thanks a bunch!